compiler=g++
flags=-g -std=c++11 -Wall -Wno-missing-braces -O3

all: countHamiltonianCyclesHeldKarp

countHamiltonianCycles: countHamiltonianCyclesHeldKarp.cpp
	$(compiler) -o countHamiltonianCyclesHeldKarp countHamiltonianCyclesHeldKarp.cpp $(flags)

clean:
	rm countHamiltonianCyclesHeldKarp

