compiler=g++
flags=-g -std=c++11 -Wall -Wno-missing-braces -O3

all: connectivity2Filter

connectivity2Filter: connectivity2Filter.cpp
	$(compiler) -o connectivity2Filter connectivity2Filter.cpp $(flags)

clean:
	rm connectivity2Filter

