compiler=g++
flags=-g -std=c++11 -Wall -Wno-missing-braces -O3

all: nearlyKRegularFilter

countHamiltonianCycles: nearlyKRegularFilter.cpp
	$(compiler) -o nearlyKRegularFilter nearlyKRegularFilter.cpp $(flags)

clean:
	rm nearlyKRegularFilter

